package com.lin.dao.mapper.guardian;

import com.lin.model.db.HeartBeat;
import com.lin.model.db.HeartBeatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HeartBeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    int countByExample(HeartBeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    int deleteByExample(HeartBeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    int insert(HeartBeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    int insertSelective(HeartBeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    List<HeartBeat> selectByExample(HeartBeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    HeartBeat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HeartBeat record, @Param("example") HeartBeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HeartBeat record, @Param("example") HeartBeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HeartBeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heart_beat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HeartBeat record);
}