package com.lin.dao.mapper.guardian;

import com.lin.model.db.LogEventStatus;
import com.lin.model.db.LogEventStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogEventStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    int countByExample(LogEventStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    int deleteByExample(LogEventStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    int insert(LogEventStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    int insertSelective(LogEventStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    List<LogEventStatus> selectByExample(LogEventStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    LogEventStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LogEventStatus record, @Param("example") LogEventStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LogEventStatus record, @Param("example") LogEventStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogEventStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogEventStatus record);
}