package com.lin.dao.mapper.guardian;

import com.lin.model.db.LogEventAbnormalData;
import com.lin.model.db.LogEventAbnormalDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogEventAbnormalDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    int countByExample(LogEventAbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    int deleteByExample(LogEventAbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    int insert(LogEventAbnormalData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    int insertSelective(LogEventAbnormalData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    List<LogEventAbnormalData> selectByExample(LogEventAbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    LogEventAbnormalData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LogEventAbnormalData record, @Param("example") LogEventAbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LogEventAbnormalData record, @Param("example") LogEventAbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogEventAbnormalData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_event_abnormal_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogEventAbnormalData record);
}