package com.lin.dao.mapper.guardian;

import com.lin.model.db.MetricItem;
import com.lin.model.db.MetricItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MetricItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    int countByExample(MetricItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    int deleteByExample(MetricItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    int insert(MetricItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    int insertSelective(MetricItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    List<MetricItem> selectByExample(MetricItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    MetricItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MetricItem record, @Param("example") MetricItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MetricItem record, @Param("example") MetricItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MetricItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MetricItem record);
}