package com.lin.dao.mapper.guardian;

import com.lin.model.db.MetricEmergencyEvent;
import com.lin.model.db.MetricEmergencyEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MetricEmergencyEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    int countByExample(MetricEmergencyEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    int deleteByExample(MetricEmergencyEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    int insert(MetricEmergencyEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    int insertSelective(MetricEmergencyEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    List<MetricEmergencyEvent> selectByExample(MetricEmergencyEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    MetricEmergencyEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MetricEmergencyEvent record, @Param("example") MetricEmergencyEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MetricEmergencyEvent record, @Param("example") MetricEmergencyEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MetricEmergencyEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MetricEmergencyEvent record);
}