package com.lin.dao.mapper.guardian;

import com.lin.model.db.MetricEmergencyHistoryEvent;
import com.lin.model.db.MetricEmergencyHistoryEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MetricEmergencyHistoryEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    int countByExample(MetricEmergencyHistoryEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    int deleteByExample(MetricEmergencyHistoryEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    int insert(MetricEmergencyHistoryEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    int insertSelective(MetricEmergencyHistoryEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    List<MetricEmergencyHistoryEvent> selectByExample(MetricEmergencyHistoryEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    MetricEmergencyHistoryEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MetricEmergencyHistoryEvent record, @Param("example") MetricEmergencyHistoryEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MetricEmergencyHistoryEvent record, @Param("example") MetricEmergencyHistoryEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MetricEmergencyHistoryEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_history_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MetricEmergencyHistoryEvent record);
}