package com.lin.dao.mapper.guardian;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubMetricGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    int countByExample(SubMetricGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    int deleteByExample(SubMetricGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    int insert(SubMetricGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    int insertSelective(SubMetricGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    List<SubMetricGroup> selectByExample(SubMetricGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    SubMetricGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SubMetricGroup record, @Param("example") SubMetricGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SubMetricGroup record, @Param("example") SubMetricGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SubMetricGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_sub_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SubMetricGroup record);
}