package com.lin.model.db;

public class HeartBeat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heart_beat.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heart_beat.metric_key
     *
     * @mbggenerated
     */
    private String metricKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heart_beat.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heart_beat.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heart_beat.id
     *
     * @return the value of heart_beat.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heart_beat.id
     *
     * @param id the value for heart_beat.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heart_beat.metric_key
     *
     * @return the value of heart_beat.metric_key
     *
     * @mbggenerated
     */
    public String getMetricKey() {
        return metricKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heart_beat.metric_key
     *
     * @param metricKey the value for heart_beat.metric_key
     *
     * @mbggenerated
     */
    public void setMetricKey(String metricKey) {
        this.metricKey = metricKey == null ? null : metricKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heart_beat.create_time
     *
     * @return the value of heart_beat.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heart_beat.create_time
     *
     * @param createTime the value for heart_beat.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heart_beat.update_time
     *
     * @return the value of heart_beat.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heart_beat.update_time
     *
     * @param updateTime the value for heart_beat.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}