package com.lin.model.db;

public class LogEventAbnormalData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.metric_gid
     *
     * @mbggenerated
     */
    private String metricGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.event_gid
     *
     * @mbggenerated
     */
    private String eventGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.abnormal_num
     *
     * @mbggenerated
     */
    private Integer abnormalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.abnormal_data
     *
     * @mbggenerated
     */
    private String abnormalData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_event_abnormal_data.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.id
     *
     * @return the value of log_event_abnormal_data.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.id
     *
     * @param id the value for log_event_abnormal_data.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.gid
     *
     * @return the value of log_event_abnormal_data.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.gid
     *
     * @param gid the value for log_event_abnormal_data.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.create_time
     *
     * @return the value of log_event_abnormal_data.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.create_time
     *
     * @param createTime the value for log_event_abnormal_data.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.metric_gid
     *
     * @return the value of log_event_abnormal_data.metric_gid
     *
     * @mbggenerated
     */
    public String getMetricGid() {
        return metricGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.metric_gid
     *
     * @param metricGid the value for log_event_abnormal_data.metric_gid
     *
     * @mbggenerated
     */
    public void setMetricGid(String metricGid) {
        this.metricGid = metricGid == null ? null : metricGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.event_gid
     *
     * @return the value of log_event_abnormal_data.event_gid
     *
     * @mbggenerated
     */
    public String getEventGid() {
        return eventGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.event_gid
     *
     * @param eventGid the value for log_event_abnormal_data.event_gid
     *
     * @mbggenerated
     */
    public void setEventGid(String eventGid) {
        this.eventGid = eventGid == null ? null : eventGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.level
     *
     * @return the value of log_event_abnormal_data.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.level
     *
     * @param level the value for log_event_abnormal_data.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.description
     *
     * @return the value of log_event_abnormal_data.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.description
     *
     * @param description the value for log_event_abnormal_data.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.abnormal_num
     *
     * @return the value of log_event_abnormal_data.abnormal_num
     *
     * @mbggenerated
     */
    public Integer getAbnormalNum() {
        return abnormalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.abnormal_num
     *
     * @param abnormalNum the value for log_event_abnormal_data.abnormal_num
     *
     * @mbggenerated
     */
    public void setAbnormalNum(Integer abnormalNum) {
        this.abnormalNum = abnormalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.abnormal_data
     *
     * @return the value of log_event_abnormal_data.abnormal_data
     *
     * @mbggenerated
     */
    public String getAbnormalData() {
        return abnormalData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.abnormal_data
     *
     * @param abnormalData the value for log_event_abnormal_data.abnormal_data
     *
     * @mbggenerated
     */
    public void setAbnormalData(String abnormalData) {
        this.abnormalData = abnormalData == null ? null : abnormalData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_event_abnormal_data.remark
     *
     * @return the value of log_event_abnormal_data.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_event_abnormal_data.remark
     *
     * @param remark the value for log_event_abnormal_data.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}