package com.lin.model.db;

public class MetricEmergencyEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.group_gid
     *
     * @mbggenerated
     */
    private String groupGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.sub_group_gid
     *
     * @mbggenerated
     */
    private String subGroupGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.metric_gid
     *
     * @mbggenerated
     */
    private String metricGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.abnormal_num
     *
     * @mbggenerated
     */
    private Integer abnormalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.abnormal_data
     *
     * @mbggenerated
     */
    private String abnormalData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_event.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.id
     *
     * @return the value of metric_emergency_event.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.id
     *
     * @param id the value for metric_emergency_event.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.gid
     *
     * @return the value of metric_emergency_event.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.gid
     *
     * @param gid the value for metric_emergency_event.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.group_gid
     *
     * @return the value of metric_emergency_event.group_gid
     *
     * @mbggenerated
     */
    public String getGroupGid() {
        return groupGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.group_gid
     *
     * @param groupGid the value for metric_emergency_event.group_gid
     *
     * @mbggenerated
     */
    public void setGroupGid(String groupGid) {
        this.groupGid = groupGid == null ? null : groupGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.sub_group_gid
     *
     * @return the value of metric_emergency_event.sub_group_gid
     *
     * @mbggenerated
     */
    public String getSubGroupGid() {
        return subGroupGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.sub_group_gid
     *
     * @param subGroupGid the value for metric_emergency_event.sub_group_gid
     *
     * @mbggenerated
     */
    public void setSubGroupGid(String subGroupGid) {
        this.subGroupGid = subGroupGid == null ? null : subGroupGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.create_time
     *
     * @return the value of metric_emergency_event.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.create_time
     *
     * @param createTime the value for metric_emergency_event.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.update_time
     *
     * @return the value of metric_emergency_event.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.update_time
     *
     * @param updateTime the value for metric_emergency_event.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.metric_gid
     *
     * @return the value of metric_emergency_event.metric_gid
     *
     * @mbggenerated
     */
    public String getMetricGid() {
        return metricGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.metric_gid
     *
     * @param metricGid the value for metric_emergency_event.metric_gid
     *
     * @mbggenerated
     */
    public void setMetricGid(String metricGid) {
        this.metricGid = metricGid == null ? null : metricGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.status
     *
     * @return the value of metric_emergency_event.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.status
     *
     * @param status the value for metric_emergency_event.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.level
     *
     * @return the value of metric_emergency_event.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.level
     *
     * @param level the value for metric_emergency_event.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.description
     *
     * @return the value of metric_emergency_event.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.description
     *
     * @param description the value for metric_emergency_event.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.abnormal_num
     *
     * @return the value of metric_emergency_event.abnormal_num
     *
     * @mbggenerated
     */
    public Integer getAbnormalNum() {
        return abnormalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.abnormal_num
     *
     * @param abnormalNum the value for metric_emergency_event.abnormal_num
     *
     * @mbggenerated
     */
    public void setAbnormalNum(Integer abnormalNum) {
        this.abnormalNum = abnormalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.abnormal_data
     *
     * @return the value of metric_emergency_event.abnormal_data
     *
     * @mbggenerated
     */
    public String getAbnormalData() {
        return abnormalData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.abnormal_data
     *
     * @param abnormalData the value for metric_emergency_event.abnormal_data
     *
     * @mbggenerated
     */
    public void setAbnormalData(String abnormalData) {
        this.abnormalData = abnormalData == null ? null : abnormalData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_event.remark
     *
     * @return the value of metric_emergency_event.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_event.remark
     *
     * @param remark the value for metric_emergency_event.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "MetricEmergencyEvent{" +
                "id=" + id +
                ", gid='" + gid + '\'' +
                ", groupGid='" + groupGid + '\'' +
                ", subGroupGid='" + subGroupGid + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", metricGid='" + metricGid + '\'' +
                ", status=" + status +
                ", level=" + level +
                ", description='" + description + '\'' +
                ", abnormalNum=" + abnormalNum +
                ", abnormalData='" + abnormalData + '\'' +
                ", remark='" + remark + '\'' +
                '}';
    }
}