package com.lin.model.db;

public class MetricItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.group_gid
     *
     * @mbggenerated
     */
    private String groupGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.sub_group_gid
     *
     * @mbggenerated
     */
    private String subGroupGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.metric_key
     *
     * @mbggenerated
     */
    private String metricKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_item.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.id
     *
     * @return the value of metric_item.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.id
     *
     * @param id the value for metric_item.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.gid
     *
     * @return the value of metric_item.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.gid
     *
     * @param gid the value for metric_item.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.group_gid
     *
     * @return the value of metric_item.group_gid
     *
     * @mbggenerated
     */
    public String getGroupGid() {
        return groupGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.group_gid
     *
     * @param groupGid the value for metric_item.group_gid
     *
     * @mbggenerated
     */
    public void setGroupGid(String groupGid) {
        this.groupGid = groupGid == null ? null : groupGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.sub_group_gid
     *
     * @return the value of metric_item.sub_group_gid
     *
     * @mbggenerated
     */
    public String getSubGroupGid() {
        return subGroupGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.sub_group_gid
     *
     * @param subGroupGid the value for metric_item.sub_group_gid
     *
     * @mbggenerated
     */
    public void setSubGroupGid(String subGroupGid) {
        this.subGroupGid = subGroupGid == null ? null : subGroupGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.create_time
     *
     * @return the value of metric_item.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.create_time
     *
     * @param createTime the value for metric_item.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.update_time
     *
     * @return the value of metric_item.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.update_time
     *
     * @param updateTime the value for metric_item.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.name
     *
     * @return the value of metric_item.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.name
     *
     * @param name the value for metric_item.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.metric_key
     *
     * @return the value of metric_item.metric_key
     *
     * @mbggenerated
     */
    public String getMetricKey() {
        return metricKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.metric_key
     *
     * @param metricKey the value for metric_item.metric_key
     *
     * @mbggenerated
     */
    public void setMetricKey(String metricKey) {
        this.metricKey = metricKey == null ? null : metricKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.status
     *
     * @return the value of metric_item.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.status
     *
     * @param status the value for metric_item.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.deleted
     *
     * @return the value of metric_item.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.deleted
     *
     * @param deleted the value for metric_item.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.description
     *
     * @return the value of metric_item.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.description
     *
     * @param description the value for metric_item.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_item.remark
     *
     * @return the value of metric_item.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_item.remark
     *
     * @param remark the value for metric_item.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}