package com.lin.model.db;

public class MetricEmergencyHistoryEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.group_gid
     *
     * @mbggenerated
     */
    private String groupGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.sub_group_gid
     *
     * @mbggenerated
     */
    private String subGroupGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.metric_gid
     *
     * @mbggenerated
     */
    private String metricGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.begin_time
     *
     * @mbggenerated
     */
    private Integer beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.close_time
     *
     * @mbggenerated
     */
    private Integer closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.close_status
     *
     * @mbggenerated
     */
    private Integer closeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric_emergency_history_event.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.id
     *
     * @return the value of metric_emergency_history_event.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.id
     *
     * @param id the value for metric_emergency_history_event.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.gid
     *
     * @return the value of metric_emergency_history_event.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.gid
     *
     * @param gid the value for metric_emergency_history_event.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.group_gid
     *
     * @return the value of metric_emergency_history_event.group_gid
     *
     * @mbggenerated
     */
    public String getGroupGid() {
        return groupGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.group_gid
     *
     * @param groupGid the value for metric_emergency_history_event.group_gid
     *
     * @mbggenerated
     */
    public void setGroupGid(String groupGid) {
        this.groupGid = groupGid == null ? null : groupGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.sub_group_gid
     *
     * @return the value of metric_emergency_history_event.sub_group_gid
     *
     * @mbggenerated
     */
    public String getSubGroupGid() {
        return subGroupGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.sub_group_gid
     *
     * @param subGroupGid the value for metric_emergency_history_event.sub_group_gid
     *
     * @mbggenerated
     */
    public void setSubGroupGid(String subGroupGid) {
        this.subGroupGid = subGroupGid == null ? null : subGroupGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.create_time
     *
     * @return the value of metric_emergency_history_event.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.create_time
     *
     * @param createTime the value for metric_emergency_history_event.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.update_time
     *
     * @return the value of metric_emergency_history_event.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.update_time
     *
     * @param updateTime the value for metric_emergency_history_event.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.metric_gid
     *
     * @return the value of metric_emergency_history_event.metric_gid
     *
     * @mbggenerated
     */
    public String getMetricGid() {
        return metricGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.metric_gid
     *
     * @param metricGid the value for metric_emergency_history_event.metric_gid
     *
     * @mbggenerated
     */
    public void setMetricGid(String metricGid) {
        this.metricGid = metricGid == null ? null : metricGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.begin_time
     *
     * @return the value of metric_emergency_history_event.begin_time
     *
     * @mbggenerated
     */
    public Integer getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.begin_time
     *
     * @param beginTime the value for metric_emergency_history_event.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Integer beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.close_time
     *
     * @return the value of metric_emergency_history_event.close_time
     *
     * @mbggenerated
     */
    public Integer getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.close_time
     *
     * @param closeTime the value for metric_emergency_history_event.close_time
     *
     * @mbggenerated
     */
    public void setCloseTime(Integer closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.close_status
     *
     * @return the value of metric_emergency_history_event.close_status
     *
     * @mbggenerated
     */
    public Integer getCloseStatus() {
        return closeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.close_status
     *
     * @param closeStatus the value for metric_emergency_history_event.close_status
     *
     * @mbggenerated
     */
    public void setCloseStatus(Integer closeStatus) {
        this.closeStatus = closeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric_emergency_history_event.remark
     *
     * @return the value of metric_emergency_history_event.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric_emergency_history_event.remark
     *
     * @param remark the value for metric_emergency_history_event.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "MetricEmergencyHistoryEvent{" +
                "id=" + id +
                ", gid='" + gid + '\'' +
                ", groupGid='" + groupGid + '\'' +
                ", subGroupGid='" + subGroupGid + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", metricGid='" + metricGid + '\'' +
                ", beginTime=" + beginTime +
                ", closeTime=" + closeTime +
                ", closeStatus=" + closeStatus +
                ", remark='" + remark + '\'' +
                '}';
    }
}