package com.lin.model.db;

import java.util.ArrayList;
import java.util.List;

public class MetricEmergencyEventExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public MetricEmergencyEventExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGidIsNull() {
            addCriterion("gid is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("gid is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(String value) {
            addCriterion("gid =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(String value) {
            addCriterion("gid <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(String value) {
            addCriterion("gid >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(String value) {
            addCriterion("gid >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(String value) {
            addCriterion("gid <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(String value) {
            addCriterion("gid <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLike(String value) {
            addCriterion("gid like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotLike(String value) {
            addCriterion("gid not like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<String> values) {
            addCriterion("gid in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<String> values) {
            addCriterion("gid not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(String value1, String value2) {
            addCriterion("gid between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(String value1, String value2) {
            addCriterion("gid not between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGroupGidIsNull() {
            addCriterion("group_gid is null");
            return (Criteria) this;
        }

        public Criteria andGroupGidIsNotNull() {
            addCriterion("group_gid is not null");
            return (Criteria) this;
        }

        public Criteria andGroupGidEqualTo(String value) {
            addCriterion("group_gid =", value, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidNotEqualTo(String value) {
            addCriterion("group_gid <>", value, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidGreaterThan(String value) {
            addCriterion("group_gid >", value, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidGreaterThanOrEqualTo(String value) {
            addCriterion("group_gid >=", value, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidLessThan(String value) {
            addCriterion("group_gid <", value, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidLessThanOrEqualTo(String value) {
            addCriterion("group_gid <=", value, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidLike(String value) {
            addCriterion("group_gid like", value, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidNotLike(String value) {
            addCriterion("group_gid not like", value, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidIn(List<String> values) {
            addCriterion("group_gid in", values, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidNotIn(List<String> values) {
            addCriterion("group_gid not in", values, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidBetween(String value1, String value2) {
            addCriterion("group_gid between", value1, value2, "groupGid");
            return (Criteria) this;
        }

        public Criteria andGroupGidNotBetween(String value1, String value2) {
            addCriterion("group_gid not between", value1, value2, "groupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidIsNull() {
            addCriterion("sub_group_gid is null");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidIsNotNull() {
            addCriterion("sub_group_gid is not null");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidEqualTo(String value) {
            addCriterion("sub_group_gid =", value, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidNotEqualTo(String value) {
            addCriterion("sub_group_gid <>", value, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidGreaterThan(String value) {
            addCriterion("sub_group_gid >", value, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidGreaterThanOrEqualTo(String value) {
            addCriterion("sub_group_gid >=", value, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidLessThan(String value) {
            addCriterion("sub_group_gid <", value, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidLessThanOrEqualTo(String value) {
            addCriterion("sub_group_gid <=", value, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidLike(String value) {
            addCriterion("sub_group_gid like", value, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidNotLike(String value) {
            addCriterion("sub_group_gid not like", value, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidIn(List<String> values) {
            addCriterion("sub_group_gid in", values, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidNotIn(List<String> values) {
            addCriterion("sub_group_gid not in", values, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidBetween(String value1, String value2) {
            addCriterion("sub_group_gid between", value1, value2, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andSubGroupGidNotBetween(String value1, String value2) {
            addCriterion("sub_group_gid not between", value1, value2, "subGroupGid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andMetricKeyIsNull() {
            addCriterion("metric_key is null");
            return (Criteria) this;
        }

        public Criteria andMetricKeyIsNotNull() {
            addCriterion("metric_key is not null");
            return (Criteria) this;
        }

        public Criteria andMetricKeyEqualTo(String value) {
            addCriterion("metric_key =", value, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyNotEqualTo(String value) {
            addCriterion("metric_key <>", value, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyGreaterThan(String value) {
            addCriterion("metric_key >", value, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyGreaterThanOrEqualTo(String value) {
            addCriterion("metric_key >=", value, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyLessThan(String value) {
            addCriterion("metric_key <", value, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyLessThanOrEqualTo(String value) {
            addCriterion("metric_key <=", value, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyLike(String value) {
            addCriterion("metric_key like", value, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyNotLike(String value) {
            addCriterion("metric_key not like", value, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyIn(List<String> values) {
            addCriterion("metric_key in", values, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyNotIn(List<String> values) {
            addCriterion("metric_key not in", values, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyBetween(String value1, String value2) {
            addCriterion("metric_key between", value1, value2, "metricKey");
            return (Criteria) this;
        }

        public Criteria andMetricKeyNotBetween(String value1, String value2) {
            addCriterion("metric_key not between", value1, value2, "metricKey");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumIsNull() {
            addCriterion("abnormal_num is null");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumIsNotNull() {
            addCriterion("abnormal_num is not null");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumEqualTo(Integer value) {
            addCriterion("abnormal_num =", value, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumNotEqualTo(Integer value) {
            addCriterion("abnormal_num <>", value, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumGreaterThan(Integer value) {
            addCriterion("abnormal_num >", value, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("abnormal_num >=", value, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumLessThan(Integer value) {
            addCriterion("abnormal_num <", value, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumLessThanOrEqualTo(Integer value) {
            addCriterion("abnormal_num <=", value, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumIn(List<Integer> values) {
            addCriterion("abnormal_num in", values, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumNotIn(List<Integer> values) {
            addCriterion("abnormal_num not in", values, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumBetween(Integer value1, Integer value2) {
            addCriterion("abnormal_num between", value1, value2, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalNumNotBetween(Integer value1, Integer value2) {
            addCriterion("abnormal_num not between", value1, value2, "abnormalNum");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataIsNull() {
            addCriterion("abnormal_data is null");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataIsNotNull() {
            addCriterion("abnormal_data is not null");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataEqualTo(String value) {
            addCriterion("abnormal_data =", value, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataNotEqualTo(String value) {
            addCriterion("abnormal_data <>", value, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataGreaterThan(String value) {
            addCriterion("abnormal_data >", value, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataGreaterThanOrEqualTo(String value) {
            addCriterion("abnormal_data >=", value, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataLessThan(String value) {
            addCriterion("abnormal_data <", value, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataLessThanOrEqualTo(String value) {
            addCriterion("abnormal_data <=", value, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataLike(String value) {
            addCriterion("abnormal_data like", value, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataNotLike(String value) {
            addCriterion("abnormal_data not like", value, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataIn(List<String> values) {
            addCriterion("abnormal_data in", values, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataNotIn(List<String> values) {
            addCriterion("abnormal_data not in", values, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataBetween(String value1, String value2) {
            addCriterion("abnormal_data between", value1, value2, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andAbnormalDataNotBetween(String value1, String value2) {
            addCriterion("abnormal_data not between", value1, value2, "abnormalData");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table metric_emergency_event
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table metric_emergency_event
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}